services:
  software_pro:
    container_name: software_pro
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    networks:
      - network_software_pro
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=software_pro.settings
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app

networks:
  network_software_pro:
    driver: bridge


